### ISSUE TITLE
Better Readable URLs

### ISSUE THREAD

**Issue by schiersner** [BB-Open/pkan.dcatapde#40]
**Describe the solution you'd like**

Plone objects should have meaningfull URLs:
e.g. https://datenadler.de/kategorien/dcat_collection_catalog-3
should be https://datenadler.de/kategorien/gesundheit

**Comment by volkerjaenisch** [comment]
Dear Mr. Schiersner!
![bildschirmfoto vom 2018-07-31 14-40-18](https://user-images.githubusercontent.com/2539336/43460035-b9d4a00a-94cf-11e8-867a-24a0fcb7637e.png)
You may change the URL manually by renaming the collection catalog.
Cheers,
Volker
